usecase-beta


actor administrateur 
actor auteur 
actor visiteur



UC1("consulter les categories")
UC2("ajouter categorie")
UC3("modifier une categorie")
UC4("suprime une categorie")
UC5("ceer un auteur")
UC6("valider un article")
UC7("publier  un article")



UC8("ajouter un article")
UC9("modifier un article non publie")
UC10("suprimer un article non publie")
UC11("changer son profil")
UC12("reintiliser son mot de passe")


UC13("consulter les articles")



administrateur---UC1 
administrateur---UC2
administrateur---UC3
administrateur---UC4
administrateur---UC5
administrateur---UC6
administrateur---UC7


auteur---UC8
auteur---UC9
auteur---UC10
auteur---UC11
auteur---UC12

visiteur---UC13