
sequenceDiagram

administrateur->>system:Demande l'ajout d'une catégorie
system-->>administrateur:Affiche le formulaire
administrateur->>system:Saisit les informations et valide
system-->>administrateur:Enregistre et affiche la catégorie